on:
  push:
     branches: [ master ]
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: abc
        env:
          VERSION_CODE: ${{ secrets.version_code }}
        run: echo TEST $VERSION_CODE