on:
  push:
     branches: [ master ]
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: get env
        env:
          VERSION_CODE: ${{ env.VERSION_CODE }}
        run: echo VERSION_CODE=${VERSION_CODE}
        
      - name: get secret
        env:
          VERSION_CODE: ${{ secrets.VERSION_CODE }}
        run: echo VERSION_CODE=${VERSION_CODE}

      # - name: set secret 
      #   uses: hmanzur/actions-set-secret@v2.0.0
      #   env:
      #     VERSION_CODE: ${{ secrets.VERSION_CODE }}
      #   with:
      #     name: 'MY_SECRET_NAME'
      #     value: $VERSION_CODE + 1
      #     repository: 'test'
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     org: true
      #     visibility: 'all'

  