on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    # The type of runner the job will run on
    name: Build And Deploy APK
    runs-on: ubuntu-latest
    # Steps represent the sequence of tasks using shell runners that will be executed as part of the Job
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate Release APK
#        env:
#          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: ./gradlew assembleDevelopRelease
