name: Jekyll site CI

on:
  pull_request:
    branches: [ master ]
    types: [ merged, closed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      echo "github.event.pull_request.merged = {github.event.pull_request.merged}"
      echo "github.event.pull_request.rebased = {github.event.pull_request.rebased}"
      run: |
        echo "github.event.pull_request.merged = {github.event.pull_request.merged}"
        echo "github.event.pull_request.rebased = {github.event.pull_request.rebased}"
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
