on:
  push:
     branches: [ master ]
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: get secret
        env:
          VERSION_CODE: ${{ secrets.VERSION_CODE }}
        run: echo $VERSION_CODE 


  