on:
  push:
     branches: [ master ]
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: abc
        env:
          VERSION_CODE: ${{ env.VERSION_CODE }}
        run: echo VERSION_CODE=${{ VERSION_CODE }}

  