on:
  push:
    tags:
      - 'v*.*.*.*'
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
  build:
    # The type of runner the job will run on
    name: Build And Deploy APK
    runs-on: ubuntu-latest
    # Steps represent the sequence of tasks using shell runners that will be executed as part of the Job
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate Release APK
        run: ./gradlew assembleDevelopRelease
